export const jobs = [
  {
    id: 'stripe-fe',
    title: 'Senior Frontend Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    tags: ['Remote', 'Full-time', '$160k - $210k'],
    jobType: 'remote',
    salaryMin: 160,
    salaryMax: 210,
    experienceLevel: 'senior',
    match: '98% Match',
    matchTone: 'strong',
    posted: 'Posted 2 days ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9nIL2a1yM0PuPAaxBHfE3tfrjf6gl93kDdr94JNLn6hgS9xGkWjnzx8sAhoSX0hNZIvw-FyR0H0YYQmAWUKfri_EZSyrRz0wFI7l25PtOpvsqiJnybywg0quv2FcMa_0i2uZIgXIy2odkKCAIxDexOKDfGL4sx52DdS3VcvrCEvmNZswD1N7hbgT-vRgxnnxgEf1AHJeP89Tm6Y5hPVVGkE8ZvQMfe60B8XQttfVjaltJieknz6zXARG8Mt_HCPmX_xv6iLc9hkk',
    badgeIcon: 'auto_awesome',
  },
  {
    id: 'airbnb-designer',
    title: 'Product Designer',
    company: 'Airbnb',
    location: 'Hybrid',
    tags: ['Hybrid', 'Design System', '$140k - $180k'],
    jobType: 'hybrid',
    salaryMin: 140,
    salaryMax: 180,
    experienceLevel: 'mid',
    match: '94% Match',
    matchTone: 'strong',
    posted: 'Posted 5 hours ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmh2nKAPXRo0U1v1Hl13zZFFaS5q71PCIHcrQqgXJdJWQReoerSZNF3LWDvNJrk8zuMHXuDvJOnQpDojig-f8YK4Ww4w-x3ltcPNLSJ_sNKfe16TAlZcIqGxHvuuk31dTEGxzqanCoVWaNcnHez5h-ssdveIwXbPMxusQWezS21-cZ3MXsTNbVeVpfw28wjKpm-FBpB6pSSTansjDDLUb_rhVOHAXrR0uY5L98klZJ-EpeRJJWmOTTkwsk8ZGrKavitDDjOVUT0fw',
    badgeIcon: 'auto_awesome',
  },
  {
    id: 'notion-fs',
    title: 'Full Stack Engineer',
    company: 'Notion',
    location: 'New York, NY',
    tags: ['On-site', 'Startup', '$170k - $220k'],
    jobType: 'onsite',
    salaryMin: 170,
    salaryMax: 220,
    experienceLevel: 'senior',
    match: '88% Match',
    matchTone: 'medium',
    posted: 'Posted 1 day ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjEd0RcM4R6Hrm31p_RZzhel0FmB-X1GuWJczV9LsUm6lxHfOCpoAdc0lNs0eMSC0ytP1CkX9volH_r0yUk-m3-wT4lQkrE5IBJ-fPf-okJ213kjP4KrBGNy76VxhRulIXR2pFOb565gvemDmYrhHccWcTEaXgk4OSeBtYwfkgxV-vai8YfTkBbEEd-bgJpSzu-i17k9LUstEWhLlCzb14TcXa9Zm90poavPvvzlkwbB2_GpF6hF_NB3KT_cdtYHqpxb_lzcLcpVA',
  },
  {
    id: 'spotify-be',
    title: 'Backend Developer',
    company: 'Spotify',
    location: 'Stockholm, SE',
    tags: ['Hybrid', 'Music Tech', '$130k - $160k'],
    jobType: 'hybrid',
    salaryMin: 130,
    salaryMax: 160,
    experienceLevel: 'mid',
    match: '85% Match',
    matchTone: 'medium',
    posted: 'Posted 3 days ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjjQrxuXrQmfZXCnald9oE8jT5biCTnquzbQ_lMo9GrtUxALbmkizqGLvARyQIYpQ50uaR6GvEXX7MkSAUYPRcpNFFvD6P8l9axWQXUNodQskvohCohfjKnCmX5Jybgdk8_dZyCHUpEL6wAGA5rlOdgrv3Wsv5hvicraq2HwaS2S8KD-uvy6aQGCSnSQi5ruJEjH8TgEmH8rdUZ7WxzMvCL9wfmXOKW-alBjT-BVWnIN5owsFR2KdQzXLRUx8CwO2DrT9W3BEJbR0',
  },
  {
    id: 'figma-de',
    title: 'Design Engineer',
    company: 'Figma',
    location: 'Remote',
    tags: ['Remote', 'Prototyping', '$150k - $200k'],
    jobType: 'remote',
    salaryMin: 150,
    salaryMax: 200,
    experienceLevel: 'senior',
    match: '82% Match',
    matchTone: 'muted',
    posted: 'Posted 4 days ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzdjtJktEhZjimajyglxORRo9AZVyzGsA_j-a470Zr8gLOMMgBXIlQCSllOZ2tzKweMb0tYfAfYJwOheq5SFfGFoXs0v-1_CXYPQrNzBOHCZjbEzH00th_AV3C6DxJiM-51W7jFa-28hpzKLl6zKkJVePy0gtfjHCuKwJAvtV2HUK0N6KB3nMKy2HoMc2Zqi1zSfp_OWCCtaCrYKFsYzpN4RrfzNAlzlmOx5SDuaerVHQ9-bJfp2dTbsurySFCg-THDQLURF71XwM',
  },
  {
    id: 'vercel-devrel',
    title: 'DevRel Engineer',
    company: 'Vercel',
    location: 'Remote',
    tags: ['Remote', 'Content', '$120k - $160k'],
    jobType: 'remote',
    salaryMin: 120,
    salaryMax: 160,
    experienceLevel: 'mid',
    match: '79% Match',
    matchTone: 'muted',
    posted: 'Posted 1 week ago',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXrxVLwouANR0oMvUI68wYXScmacm7k7iccc1SebB82FJF_uN0Ot9-pU26_2g3z8LFD7xWPlUgG-0NCIf3FLOknTf_YDXoXsN2_bqwXlvtisSZINvYnhSf4rwSFNDzAvrQRoQnicqhaLl4Ff2K9695bg2TdVGyDU4aqkNEwX_stn0UFj2PSdkaA-e6pp7CKSqUGtZF6A3Hfo6eISvOdg66MJ1ADXME1XWZMC_x2EQ7G5SylD1VfN9nClVSzxAVuaXLdKleEVoi7aI',
  },
  {
    id: 'google-ml',
    title: 'Machine Learning Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    tags: ['On-site', 'AI/ML', '$180k - $240k'],
    jobType: 'onsite',
    salaryMin: 180,
    salaryMax: 240,
    experienceLevel: 'senior',
    match: '91% Match',
    matchTone: 'strong',
    posted: 'Posted 2 days ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    badgeIcon: 'auto_awesome',
  },
  {
    id: 'meta-fe',
    title: 'Frontend Engineer',
    company: 'Meta',
    location: 'Remote',
    tags: ['Remote', 'React', '$170k - $230k'],
    jobType: 'remote',
    salaryMin: 170,
    salaryMax: 230,
    experienceLevel: 'mid',
    match: '87% Match',
    matchTone: 'medium',
    posted: 'Posted 1 day ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Meta_Platforms_Inc._logo.svg',
  },
  {
    id: 'amazon-sde',
    title: 'Software Development Engineer II',
    company: 'Amazon',
    location: 'Seattle, WA',
    tags: ['Hybrid', 'Cloud', '$150k - $200k'],
    jobType: 'hybrid',
    salaryMin: 150,
    salaryMax: 200,
    experienceLevel: 'mid',
    match: '84% Match',
    matchTone: 'medium',
    posted: 'Posted 6 hours ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
  },
  {
    id: 'openai-research',
    title: 'Research Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    tags: ['Hybrid', 'AI/ML', '$190k - $260k'],
    jobType: 'hybrid',
    salaryMin: 190,
    salaryMax: 260,
    experienceLevel: 'senior',
    match: '93% Match',
    matchTone: 'strong',
    posted: 'Posted 3 days ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg',
    badgeIcon: 'auto_awesome',
  },
  {
    id: 'shopify-lead',
    title: 'Lead Frontend Developer',
    company: 'Shopify',
    location: 'Remote',
    tags: ['Remote', 'Leadership', '$180k - $230k'],
    jobType: 'remote',
    salaryMin: 180,
    salaryMax: 230,
    experienceLevel: 'lead',
    match: '86% Match',
    matchTone: 'medium',
    posted: 'Posted 5 days ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Shopify_logo_2018.svg',
  },
  {
    id: 'datadog-sre',
    title: 'Site Reliability Engineer',
    company: 'Datadog',
    location: 'New York, NY',
    tags: ['Hybrid', 'SRE', '$160k - $210k'],
    jobType: 'hybrid',
    salaryMin: 160,
    salaryMax: 210,
    experienceLevel: 'senior',
    match: '83% Match',
    matchTone: 'muted',
    posted: 'Posted 1 week ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Datadog_logo.svg',
  },
  {
    id: 'doordash-pm',
    title: 'Product Manager',
    company: 'DoorDash',
    location: 'Hybrid',
    tags: ['Hybrid', 'Consumer', '$150k - $190k'],
    jobType: 'hybrid',
    salaryMin: 150,
    salaryMax: 190,
    experienceLevel: 'mid',
    match: '80% Match',
    matchTone: 'muted',
    posted: 'Posted 2 days ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/DoorDash_Logo.svg',
  },
  {
    id: 'uber-data',
    title: 'Senior Data Scientist',
    company: 'Uber',
    location: 'Remote',
    tags: ['Remote', 'Data', '$170k - $220k'],
    jobType: 'remote',
    salaryMin: 170,
    salaryMax: 220,
    experienceLevel: 'senior',
    match: '89% Match',
    matchTone: 'medium',
    posted: 'Posted 8 hours ago',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png',
  },
];

